services:
  python-app:
    build: .
    container_name: laz_2_dem
    restart: unless-stopped
    volumes:
      - app_data:/app/app/data
      - app_uploads:/app/app/uploads
      - app_outputs:/app/app/outputs
    ports:
      - "9091:9090"
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=production

volumes:
  app_data:
  app_uploads:
  app_outputs: