services:
  python-app:
    build: .
    container_name: laz_2_dem
    restart: unless-stopped
    volumes:
      - ${APP_DATA_PATH:-./app/data}:/app/app/data
      - ${APP_OUTPUTS_PATH:-./app/outputs}:/app/app/outputs
      - ${NUVENS_HOST_PATH:-./app/nuvens}:/app/app/nuvens
    ports:
      - "9091:9090"
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=production
volumes:
  app_data:
  app_outputs:
